spring:
  main:
    banner-mode: off
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  # se inhabilita el cliente eureka
  client:
    register-with-eureka: false
    fetch-registry: false
