spring:
  main:
    banner-mode: off
  application:
    name: servicio-productos
  jpa:
    hibernate:
       # import.sql
      ddl-auto: create
  # DB
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: root
    driver:
      class: oracle.jdbc.driver.OracleDriver

server:
  # puerto random
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # la instancias se generaran con un puerto random
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}    
